React Hooks Linter
BigVikingGames/Bragi pull request #12
Opened 2020-10-19 20:52 UTC by mshimokura

include the react hooks linter for eslint

2020-10-19 20:53 UTC, gaurdianaq approved these changes

2020-10-19 21:09 UTC, nickgkg requested changes
You just need to also add it the setup-local-lint.sh in the #ESLINT section
`ensure_package_exists eslint-plugin-react-hooks`

2020-10-19 21:11 UTC, nickgkg commented on package.json
> +{
I don't think this is necessary since bragi doesn't have any js/ts files anyway.  Instead it's required that the project containing the linter has a root project with this as a dev dependency

2020-10-19 21:12 UTC, nickgkg requested changes

2020-10-19 21:12 UTC, nickgkg commented on package.json
> +  "name": "@bvg/bragi",
I don't think this is necessary since bragi doesn't have any js/ts files anyway. Instead it's required that the project containing the linter has a root project with this as a dev dependency

2020-10-19 21:15 UTC, mshimokura commented on package.json
> +  "name": "@bvg/bragi",
hmm so I did this to fix this issue here: https://github.com/BigVikingGames/VirtualVikoins/runs/1277510076#step:5:207
> (The package "eslint-plugin-react-hooks" was not found when loaded as a Node module from the directory "/github/workspace/.github/linters".)

So, I could put it in the root directory of the project. But for instance, the vikoins project doesn't have a node module in the root directory.

2020-10-19 21:28 UTC, nickgkg commented on package.json
> +  "name": "@bvg/bragi",
Oh so I thought super linter was running in the root of the parent project.  I guess not

2020-10-19 21:28 UTC, nickgkg approved these changes

2020-10-19 21:29 UTC, mshimokura commented on package.json
> +  "name": "@bvg/bragi",
yeah im not sure exactly how its supposed to work. I guess if you have a repo that's only an npm package it will work that way.

2020-10-19 21:30 UTC, nickgkg commented
you do need to merge in master in order for it to pass the linter

2020-10-20 13:22 UTC, mshimokura commented
im fairly sure the linter would pass if it wasnt having branch woes.

2020-10-20 13:22 UTC, merged